### ISSUE TITLE
[Feature Request] Default MOTD

### ISSUE THREAD

**Issue by MrOrange9-JCT** [jmanpenilla/MiniMOTD#19]
I would like a default MOTD for outdated clients, because sometimes, the downsample RGB Colors look so wrong.

Add an option to disable downsample RGB Colors for outdated clients and enable a "default" motd for outdated clients with default Minecraft colors and formating (no gradient, no RGB)

The config would look something like thins
```yaml
    # Explanation here
    defaultMotdEnabled: true
    defaultMotd:
     - "<bold><aqua>This is a default MOTD</aqua></bold>"
```
